"""Localization-coverage guard: the English-only surface can't silently grow.

Phase 5 finding: the i18n catalog is internally complete (every entry has all
five languages) but covers only part of the rendered surface — a large body of
card strings render English-only in every language. That debt was invisible.

This suite makes it a tracked artifact. It renders every frozen card fixture in
each non-English language and records which source strings the catalog does NOT
translate (via i18n's own miss telemetry), then compares that set to a committed
baseline. A NEW English-only string added later fails the test, forcing a
conscious choice: translate it, or add it to the baseline as accepted-English.

This is the i18n equivalent of the render snapshots — it does not fix the debt,
it stops it drifting. Routing safety (reply-keyboard labels round-tripping in
every language) is locked separately and comprehensively by
tests/test_i18n_reply_routing.py; this suite is about coverage, not routing.

Regenerate the baseline after an intended change::

    NADO_UPDATE_SNAPSHOTS=1 .venv/bin/python -m pytest \
        tests/handlers/test_i18n_coverage.py

and review the diff — new English-only strings should be a deliberate decision.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from _stubs import install_test_stubs

install_test_stubs()

import src.nadobro.i18n as i18n  # noqa: E402
from src.nadobro.handlers import formatters as F  # noqa: E402
from tests.handlers.formatter_fixtures import CASES  # noqa: E402

BASELINE_PATH = Path(__file__).parent / "__snapshots__" / "i18n_english_only.txt"
UPDATE = os.environ.get("NADO_UPDATE_SNAPSHOTS") == "1"
NON_EN = ["zh", "fr", "ar", "ru", "ko"]


def _english_only_strings() -> list[str]:
    """Source strings the catalog leaves untranslated, from the frozen fixtures.

    Deterministic: driven only by CASES + the formatters' own _loc calls, with
    no venue/DB/product-catalog dependency, so the set is a pure function of the
    committed code and fixtures.
    """
    # Freeze the two clocks so a card that renders an age/heartbeat is stable.
    orig_uptime, orig_age, orig_time = F._fmt_uptime, F._fmt_age_seconds, F.time.time
    F._fmt_uptime = lambda _s: "6h 30m" if _s else "—"
    F._fmt_age_seconds = lambda ts: "12s" if ts else "—"
    F.time.time = lambda: 1_756_000_012.0
    try:
        i18n.clear_missing_translations()
        for lang in NON_EN:
            with i18n.language_context(lang):
                for _cid, fn_name, args, kwargs in CASES:
                    try:
                        getattr(F, fn_name)(*args, **kwargs)
                    except Exception:
                        pass
        return sorted({src for _lang, src in i18n.get_missing_translations()})
    finally:
        F._fmt_uptime, F._fmt_age_seconds, F.time.time = orig_uptime, orig_age, orig_time


def _serialise(strings: list[str]) -> str:
    header = [
        "# English-only card strings (localization debt baseline)",
        "# Generated by tests/handlers/test_i18n_coverage.py. Do not hand-edit.",
        "# Each line is a source string with no catalog translation in zh/fr/ar/ru/ko.",
        f"# Count: {len(strings)}",
        "",
    ]
    # repr() keeps escapes/newlines legible and diff-stable.
    return "\n".join(header + [repr(s) for s in strings]) + "\n"


def test_english_only_surface_matches_baseline():
    current = _english_only_strings()
    serialised = _serialise(current)
    if UPDATE or not BASELINE_PATH.exists():
        BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
        BASELINE_PATH.write_text(serialised, encoding="utf-8")
        if not UPDATE:
            pytest.fail(f"baseline created at {BASELINE_PATH}; review and re-run.")
        return

    committed = BASELINE_PATH.read_text(encoding="utf-8")
    baseline = [
        eval(line)  # noqa: S307 - our own repr() output, trusted test data
        for line in committed.splitlines()
        if line and not line.startswith("#")
    ]
    new = sorted(set(current) - set(baseline))
    fixed = sorted(set(baseline) - set(current))
    assert not new and not fixed, (
        "the English-only card surface changed.\n"
        + (f"  NEW untranslated strings (translate them, or accept into the baseline):\n"
           + "\n".join(f"    + {s!r}" for s in new) if new else "")
        + (("\n" if new else "")
           + "  now-translated / removed strings (regenerate the baseline):\n"
           + "\n".join(f"    - {s!r}" for s in fixed) if fixed else "")
        + "\n\nRegenerate with NADO_UPDATE_SNAPSHOTS=1 after a deliberate change."
    )


# NOTE: routing safety — reply-keyboard labels round-tripping in every language —
# is deliberately NOT asserted here. It is covered comprehensively by
# tests/test_i18n_reply_routing.py against the real resolve path. This suite is
# strictly about body-text coverage debt; a bare word like "Trade" can appear
# both here (as a section label) and as a legacy compat alias in
# REPLY_BUTTON_MAP without being a routing hazard, so cross-checking the two
# sets would only produce false alarms.
