"""Golden-render snapshots for every card formatter.

Phase 0 of the interface overhaul. This suite ships NO behaviour change — its
only job is to make the later phases reviewable:

* Phase 1 replaces rule widths, icons, nav labels and number formats across 42
  formatters. That is a mechanical edit over ~2k lines of card text. Without a
  golden diff, "it still renders fine" is an assertion; with one, every changed
  byte has to be justified.
* Phase 3 adds freshness lines. The gate for that phase is that snapshot diffs
  only ADD lines and never alter an existing numeric field — which is only
  checkable if the numbers were pinned first.

Regenerate after an intended change::

    NADO_UPDATE_SNAPSHOTS=1 .venv/bin/python -m pytest \
        tests/handlers/test_formatter_snapshots.py

then read the diff in ``__snapshots__/formatters.snap.md`` before committing it.
A regeneration with an unexplained diff is a failed review, not a passing test.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from _stubs import install_test_stubs

install_test_stubs()

from src.nadobro.handlers import formatters as F  # noqa: E402
from tests.handlers.formatter_fixtures import CASES  # noqa: E402

SNAPSHOT_PATH = Path(__file__).parent / "__snapshots__" / "formatters.snap.md"
UPDATE = os.environ.get("NADO_UPDATE_SNAPSHOTS") == "1"

# Frozen clock values. The two time-dependent helpers in ``formatters`` compute
# a duration from "now"; pinning them keeps the snapshot stable without
# pretending the cards have no clock in them.
FROZEN_UPTIME = "6h 30m"
FROZEN_AGE = "12s"
# STATUS_RUNNING.worker_last_heartbeat + 12 → heartbeat age 12s → "live" state.
FROZEN_NOW = 1_756_000_012.0


@pytest.fixture(autouse=True)
def _deterministic_render(monkeypatch):
    """Pin the clock and the language so a snapshot is a pure function of input."""
    monkeypatch.setattr(F, "_fmt_uptime", lambda _started_at: FROZEN_UPTIME if _started_at else "—")
    monkeypatch.setattr(F, "_fmt_age_seconds", lambda ts: FROZEN_AGE if ts else "—")
    # Freeze wall-clock so the status card's heartbeat-freshness line (which
    # compares time.time() to worker_last_heartbeat) is deterministic. The
    # STATUS_RUNNING fixture's heartbeat is FROZEN_NOW - 12s, so it renders the
    # "live" state; _fmt_age_seconds is already stubbed to "12s" to match.
    monkeypatch.setattr(F.time, "time", lambda: FROZEN_NOW)
    # Cards route every string through i18n; pin to English so a translation
    # edit cannot silently rewrite the snapshot of an unrelated screen.
    monkeypatch.setattr(F, "get_active_language", lambda: "en")
    monkeypatch.setattr(F, "localize_text", lambda text, _lang=None: text)
    yield


def _render_all() -> str:
    """Render every registered case into one reviewable document."""
    chunks: list[str] = [
        "# Card render snapshots",
        "",
        "Generated by `tests/handlers/test_formatter_snapshots.py`. Do not hand-edit.",
        "Regenerate with `NADO_UPDATE_SNAPSHOTS=1 pytest tests/handlers/test_formatter_snapshots.py`.",
        "",
        f"{len(CASES)} cases across {len({c[1] for c in CASES})} formatters.",
        "",
    ]
    for case_id, fn_name, args, kwargs in CASES:
        fn = getattr(F, fn_name)
        rendered = fn(*args, **kwargs)
        if not isinstance(rendered, str):
            rendered = repr(rendered)
        chunks.append(f"## {case_id}")
        chunks.append(f"`{fn_name}`")
        chunks.append("")
        chunks.append("```")
        chunks.append(rendered)
        chunks.append("```")
        chunks.append("")
    return "\n".join(chunks) + "\n"


def test_every_formatter_has_a_snapshot_case():
    """A new card must arrive with a snapshot, or Phase 1 will refactor it blind."""
    public = {
        name
        for name, obj in vars(F).items()
        if name.startswith("fmt_") and callable(obj) and not name.startswith("_")
    }
    covered = {fn_name for _cid, fn_name, _a, _k in CASES}
    missing = sorted(public - covered)
    assert not missing, (
        "these formatters render user-facing cards but have no snapshot case: "
        f"{missing}. Add one to tests/handlers/formatter_fixtures.py::CASES."
    )


def test_case_ids_are_unique():
    ids = [c[0] for c in CASES]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    assert not dupes, f"duplicate snapshot case ids would silently overwrite each other: {dupes}"


def test_no_formatter_raises():
    """Every card must render for both its populated and its empty branch."""
    failures = []
    for case_id, fn_name, args, kwargs in CASES:
        try:
            getattr(F, fn_name)(*args, **kwargs)
        except Exception as exc:  # pragma: no cover - the assert reports it
            failures.append(f"{case_id} ({fn_name}): {type(exc).__name__}: {exc}")
    assert not failures, "formatters raised while rendering:\n" + "\n".join(failures)


def test_rendered_cards_match_snapshot():
    current = _render_all()
    if UPDATE or not SNAPSHOT_PATH.exists():
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(current, encoding="utf-8")
        if not UPDATE:
            pytest.fail(
                f"snapshot did not exist and was created at {SNAPSHOT_PATH}. "
                "Review it and re-run."
            )
        return

    expected = SNAPSHOT_PATH.read_text(encoding="utf-8")
    if current == expected:
        return

    import difflib

    diff = "\n".join(
        difflib.unified_diff(
            expected.splitlines(),
            current.splitlines(),
            fromfile="snapshot (committed)",
            tofile="render (current code)",
            lineterm="",
            n=3,
        )
    )
    pytest.fail(
        "rendered cards drifted from the committed snapshot.\n\n"
        "If the change is intended, regenerate with:\n"
        "  NADO_UPDATE_SNAPSHOTS=1 .venv/bin/python -m pytest "
        "tests/handlers/test_formatter_snapshots.py\n"
        "and review the resulting diff before committing.\n\n" + diff
    )
